version: 1.0.{build}
environment:
  AVRAW: https://raw.githubusercontent.com/appveyor/ci/master/scripts/
  AVFILE: enable-desktop.ps1
  KVMASTER: 1.9.2
  LATESTPY2: 2.7.13
  LATESTPY34: 3.4.6
  LATESTPY35: 3.5.3
  LATESTPY36: 3.6.0

  matrix:
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 1
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 1
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 1

  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 1
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 1
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 1

  - PY: 34
    ARCH: 86
    MASTER: 0
    ADMIN: 0
  - PY: 34
    ARCH: 86
    MASTER: 1
    ADMIN: 0

  - PY: 34
    ARCH: 64
    MASTER: 0
    ADMIN: 0
  - PY: 34
    ARCH: 64
    MASTER: 1
    ADMIN: 0

  - PY: 35
    ARCH: 86
    MASTER: 1
    ADMIN: 0
  - PY: 35
    ARCH: 86
    MASTER: 1
    ADMIN: 1

  - PY: 35
    ARCH: 64
    MASTER: 1
    ADMIN: 0
  - PY: 35
    ARCH: 64
    MASTER: 1
    ADMIN: 1

  - PY: 36
    ARCH: 86
    MASTER: 1
    ADMIN: 0
  - PY: 36
    ARCH: 86
    MASTER: 1
    ADMIN: 1

  - PY: 36
    ARCH: 64
    MASTER: 1
    ADMIN: 0
  - PY: 36
    ARCH: 64
    MASTER: 1
    ADMIN: 1

install:
- ps: iex ((new-object net.webclient).DownloadString($env:AVRAW+$env:AVFILE))

build_script:
- cmd:
    setlocal ENABLEDELAYEDEXPANSION

    rem Check vars for environment generation first

    if not defined PY (echo Set env var "PY" to -> 27, 34, 35, 36, 37 & exit 1)

    if not defined ARCH (echo Set env var "ARCH" to -> 86, 64 & exit 1)

    echo Py %PY%, arch %ARCH%, master %MASTER% admin %ADMIN%
    designer %DESIGNER%, shortcuts %SHORTCUTS%, cd %CD%

    mkdir %cd%\kivy_python

    copy %cd%\kivy.bat %cd%\kivy_python\kivy.bat

    cd %cd%\kivy_python

    rem batupdate test

    kivy version > _ver

    set /p new_ver=<_ver && del _ver

    set up_com=::Version

    rem just because appveyor is nuts about single colons

    powershell -c "[char]58" > _colon

    set /p colon=<_colon && del _colon

    set up_com=%up_com%%colon% %new_ver%

    set up_ver=set installerversion=%new_ver%

    powershell -c "[string](%new_ver%-0.1)" > _calc

    set /p old_ver=<_calc && del _calc

    for /F "delims=" %%l in (%cd%\kivy.bat) do (if "%%l"=="%up_com%" (
        echo ::Version%colon% %old_ver%>> old.bat
    ) else if "%%l"=="%up_ver%" (
        echo set installerversion=%old_ver%>> old.bat
    ) else (echo %%l>> old.bat))

    del %cd%\kivy.bat && move %cd%\old.bat %cd%\kivy.bat

    rem batch test

    set DEBUG=1

    set choice_python=3

    if "%PY%"=="27" (
        set choice_python=2&& set py2=%LATESTPY2%
    ) else if "%PY%"=="34" (
        set py3=%LATESTPY34%
    ) else if "%PY%"=="35" (
        set py3=%LATESTPY35%
    ) else if "%PY%"=="36" (
        set py3=%LATESTPY36%
    )

    set choice_kivy=y

    set choice_master=n

    if "%MASTER%"=="1" (
        set choice_master=y
    )

    set choice_privileges=n

    if "%ADMIN%"=="1" (
        set choice_privileges=y
    )

    set choice_dsgn=n

    if "%DESIGNER%"=="1" (
        set choice_dsgn=y
    )

    set choice_shrt=n

    if "%SHORTCUTS%"=="1" (
        set choice_shrt=y
    )

    set master=%KVMASTER%

    set choice_ext=n

    set choice_gst=n

    REM set 'arch32' with pipe to silence other 'set /p'

    if "%ARCH%"=="86" (
        (echo y)|kivy
    ) else if "%ARCH%"=="64" (
        (echo n)|kivy
    )

    set QL=%appdata%\Microsoft\Internet Explorer\Quick Launch

    set ST=%appdata%\Microsoft\Windows\SendTo

    dir "%QL%"

    if "%SHORTCUTS%"=="1" (
        if not exist "%QL%\Kivy%PY%.bat" exit /B 1
    )

    dir "%ST%"

    if "%SHORTCUTS%"=="1" (
        if not exist "%ST%\Kivy%PY%.bat" exit /B 1
    )

    echo Installer config

    type %cd%\config.kivyinstaller

    kivy batupdate

    kivy version > _ver

    set /p new_ver=<_ver && del _ver

    if not %new_ver% gtr %old_ver% ( exit 1 )
